export const roadIncidents = [
  { value: "road_accident", title: "Road Accident" },
  { value: "road_rage", title: "Road Rage" },
  { value: "wrong_side_driving", title: "Wrong-side Driving" },
  { value: "rash_driving", title: "Rash Driving" },
  { value: "overspeeding", title: "Overspeeding" },
  { value: "hit_and_run", title: "Hit and Run" },
  { value: "pedestrian_accident", title: "Pedestrian Accident" },
  { value: "drunk_driving", title: "Drunk Driving" },
  { value: "reckless_driving", title: "Reckless Driving" },
  { value: "tailgating", title: "Tailgating" },
  { value: "illegal_overtaking", title: "Illegal Overtaking" },
  { value: "running_red_light", title: "Running Red Light" },
  { value: "distracted_driving", title: "Distracted Driving" },
  { value: "illegal_u_turn", title: "Illegal U-turn" },
  { value: "failure_to_yield", title: "Failure to Yield" },
  { value: "lane_violation", title: "Lane Violation" },
  { value: "no_seatbelt", title: "No Seatbelt" },
  { value: "motorbike_on_pavement", title: "Motorbike on Pavement" },
  { value: "no_helmet", title: "No Helmet" },
  { value: "parking_violation", title: "Parking Violation" },
  { value: "high_beam_violation", title: "High Beam Violation" },
];
